spring:
  application:
    name: MealSubscription

  datasource :
    url : jdbc:mysql://localhost:3306/meal_db
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

